[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = 'black'

[tool.coverage.run]
branch = true
parallel = true
source = ["pandas_faker"]
command_line = "-m pytest"

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
